services:
  app:
    build: .
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/postgresql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./databases/postgresql/populate_data.sql:/docker-entrypoint-initdb.d/populate_data.sql
      - ./databases/postgresql/recipe_db.sql:/docker-entrypoint-initdb.d/recipe_db.sql
      - ./databases/postgresql/user_data.sql:/docker-entrypoint-initdb.d/user_data.sql


  prometheus:
    image: prom/prometheus:latest
    ports:
        - 9090:9090    

  mongo:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local
